services:
  backend:
    container_name: backend-container-dev
    # image: backend-image-dev
    build:
      context: backend
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    restart: always
  frontend:
    container_name: frontend-container-dev
    # image: frontend-image-dev
    build:
      context: frontend
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "3000:3000"
    restart: always
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    env_file: .env
    restart: always
