services:
  backend:
    container_name: backend-container-prod
    # image: backend-image-prod
    build:
      context: backend
      dockerfile: Dockerfile.pub
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    restart: always
  frontend:
    container_name: frontend-container-prod
    # image: frontend-image-prod
    build:
      context: frontend
      dockerfile: Dockerfile.pub
    env_file: .env
    ports:
      - "3000:80"
    restart: always
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    env_file: .env
    restart: always
